### ISSUE TITLE
Deprecations on PHP 8.1

### ISSUE THREAD

**Issue by szepeviktor** [deviodigital/dispensary-age-verification#2]
Query Monitor plugin shows deprecations.

![image](https://github.com/user-attachments/assets/826f06c7-ab40-48c4-8735-e831e7b57e30)

@robertdevore Would you merge a PR fixing it and release a new version?

**Comment by robertdevore** [comment]
@szepeviktor It's been fixed locally already and will be pushed in a new update with a few other changes soon. Thanks for bringing this up 🤘

**Comment by szepeviktor** [comment]
Glad to contribute.
